print ("=" * 40)
print ("*********AVEDEX*********")
print ("=" * 40)
nome_usuario = input(" Digite o seu nome: ") . strip()
cidade_usuario = input("Digite o nome da sua cidade:"). strip ()
ave_favorita = input("Digite o nome da sua ave favorita:"). strip()

print("-" *40)
print("      DADOS INICIAIS    ")
print("-" *40)
print(f"\n Usuário: {nome_usuario}!")
print(f"\n Cidade: {cidade_usuario}!")
print(f"\n Ave favorita: {ave_favorita}!")

print()
print(f"\n Olá, {nome_usuario}!")
print("Bem-vindo ao Avedex")
print("aqui vamos aprender as boas práticas de programação")
print("e também vamos aprender sobre as aves brasileiras")
